/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big.ide.contentassist.antlr;

import ac.at.tuwien.big.ide.contentassist.antlr.internal.InternalScmlParser;
import ac.at.tuwien.big.services.ScmlGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class ScmlParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(ScmlGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, ScmlGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInfrastructureComponentAccess().getAlternatives(), "rule__InfrastructureComponent__Alternatives");
			builder.put(grammarAccess.getDeviceAccess().getAlternatives(), "rule__Device__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
			builder.put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
			builder.put(grammarAccess.getParameterTypeAccess().getAlternatives(), "rule__ParameterType__Alternatives");
			builder.put(grammarAccess.getPrincipleTypeAccess().getAlternatives(), "rule__PrincipleType__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getStatusAccess().getAlternatives(), "rule__Status__Alternatives");
			builder.put(grammarAccess.getSmartCityAccess().getGroup(), "rule__SmartCity__Group__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_4(), "rule__SmartCity__Group_4__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_4_3(), "rule__SmartCity__Group_4_3__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_5(), "rule__SmartCity__Group_5__0");
			builder.put(grammarAccess.getSmartCityAccess().getGroup_5_3(), "rule__SmartCity__Group_5_3__0");
			builder.put(grammarAccess.getCategoryAccess().getGroup(), "rule__Category__Group__0");
			builder.put(grammarAccess.getCategoryAccess().getGroup_1(), "rule__Category__Group_1__0");
			builder.put(grammarAccess.getCategoryAccess().getGroup_1_4(), "rule__Category__Group_1_4__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_0(), "rule__Project__Group_0__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_0_1(), "rule__Project__Group_0_1__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_0_1_3(), "rule__Project__Group_0_1_3__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_0_3(), "rule__Project__Group_0_3__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_0_3_3(), "rule__Project__Group_0_3_3__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_1(), "rule__Project__Group_1__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_1_0(), "rule__Project__Group_1_0__0");
			builder.put(grammarAccess.getProjectAccess().getGroup_1_0_3(), "rule__Project__Group_1_0_3__0");
			builder.put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_0(), "rule__KPIMeasurementDevice__Group_0__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_0_1(), "rule__KPIMeasurementDevice__Group_0_1__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_0_1_4(), "rule__KPIMeasurementDevice__Group_0_1_4__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_0_3(), "rule__KPIMeasurementDevice__Group_0_3__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_0_3_3(), "rule__KPIMeasurementDevice__Group_0_3_3__0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getGroup_1(), "rule__KPIMeasurementDevice__Group_1__0");
			builder.put(grammarAccess.getLocationAccess().getGroup(), "rule__Location__Group__0");
			builder.put(grammarAccess.getDataValueAccess().getGroup(), "rule__DataValue__Group__0");
			builder.put(grammarAccess.getDataValueAccess().getGroup_1(), "rule__DataValue__Group_1__0");
			builder.put(grammarAccess.getDataValueAccess().getGroup_9(), "rule__DataValue__Group_9__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_0(), "rule__Parameter__Group_0__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_1(), "rule__Parameter__Group_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_2(), "rule__Parameter__Group_2__0");
			builder.put(grammarAccess.getParameterAccess().getGroup_2_0(), "rule__Parameter__Group_2_0__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_0(), "rule__BuildingComponent__Group_0__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_0_3(), "rule__BuildingComponent__Group_0_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_1(), "rule__BuildingComponent__Group_1__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_1_3(), "rule__BuildingComponent__Group_1_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_2(), "rule__BuildingComponent__Group_2__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_3(), "rule__BuildingComponent__Group_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_3_3(), "rule__BuildingComponent__Group_3_3__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_4(), "rule__BuildingComponent__Group_4__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_5(), "rule__BuildingComponent__Group_5__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_5_0(), "rule__BuildingComponent__Group_5_0__0");
			builder.put(grammarAccess.getBuildingComponentAccess().getGroup_5_0_3(), "rule__BuildingComponent__Group_5_0_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_0(), "rule__TransportationComponent__Group_0__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_0_3(), "rule__TransportationComponent__Group_0_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_1(), "rule__TransportationComponent__Group_1__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_1_3(), "rule__TransportationComponent__Group_1_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_2(), "rule__TransportationComponent__Group_2__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_3(), "rule__TransportationComponent__Group_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_3_3(), "rule__TransportationComponent__Group_3_3__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_4(), "rule__TransportationComponent__Group_4__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_5(), "rule__TransportationComponent__Group_5__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_5_0(), "rule__TransportationComponent__Group_5_0__0");
			builder.put(grammarAccess.getTransportationComponentAccess().getGroup_5_0_3(), "rule__TransportationComponent__Group_5_0_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_0(), "rule__EnvironmentalComponent__Group_0__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_0_3(), "rule__EnvironmentalComponent__Group_0_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_1(), "rule__EnvironmentalComponent__Group_1__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_1_3(), "rule__EnvironmentalComponent__Group_1_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_2(), "rule__EnvironmentalComponent__Group_2__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_3(), "rule__EnvironmentalComponent__Group_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_3_3(), "rule__EnvironmentalComponent__Group_3_3__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_4(), "rule__EnvironmentalComponent__Group_4__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_5(), "rule__EnvironmentalComponent__Group_5__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_5_0(), "rule__EnvironmentalComponent__Group_5_0__0");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getGroup_5_0_3(), "rule__EnvironmentalComponent__Group_5_0_3__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
			builder.put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getGroup(), "rule__GoalReferenceValue__Group__0");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getGroup_10(), "rule__GoalReferenceValue__Group_10__0");
			builder.put(grammarAccess.getAggregatedValueAccess().getGroup(), "rule__AggregatedValue__Group__0");
			builder.put(grammarAccess.getAggregatedValueAccess().getGroup_10(), "rule__AggregatedValue__Group_10__0");
			builder.put(grammarAccess.getBasisAccess().getGroup(), "rule__Basis__Group__0");
			builder.put(grammarAccess.getSensorAccess().getGroup(), "rule__Sensor__Group__0");
			builder.put(grammarAccess.getActuatorAccess().getGroup(), "rule__Actuator__Group__0");
			builder.put(grammarAccess.getSmartCityAccess().getNameAssignment_2(), "rule__SmartCity__NameAssignment_2");
			builder.put(grammarAccess.getSmartCityAccess().getCategoryAssignment_4_2(), "rule__SmartCity__CategoryAssignment_4_2");
			builder.put(grammarAccess.getSmartCityAccess().getCategoryAssignment_4_3_1(), "rule__SmartCity__CategoryAssignment_4_3_1");
			builder.put(grammarAccess.getSmartCityAccess().getProjectAssignment_5_2(), "rule__SmartCity__ProjectAssignment_5_2");
			builder.put(grammarAccess.getSmartCityAccess().getProjectAssignment_5_3_1(), "rule__SmartCity__ProjectAssignment_5_3_1");
			builder.put(grammarAccess.getCategoryAccess().getNameAssignment_0(), "rule__Category__NameAssignment_0");
			builder.put(grammarAccess.getCategoryAccess().getSDGAssignment_1_3(), "rule__Category__SDGAssignment_1_3");
			builder.put(grammarAccess.getCategoryAccess().getSDGAssignment_1_4_1(), "rule__Category__SDGAssignment_1_4_1");
			builder.put(grammarAccess.getProjectAccess().getNameAssignment_0_0(), "rule__Project__NameAssignment_0_0");
			builder.put(grammarAccess.getProjectAccess().getCategoryAssignment_0_1_2(), "rule__Project__CategoryAssignment_0_1_2");
			builder.put(grammarAccess.getProjectAccess().getCategoryAssignment_0_1_3_1(), "rule__Project__CategoryAssignment_0_1_3_1");
			builder.put(grammarAccess.getProjectAccess().getComponentAssignment_0_3_2(), "rule__Project__ComponentAssignment_0_3_2");
			builder.put(grammarAccess.getProjectAccess().getComponentAssignment_0_3_3_1(), "rule__Project__ComponentAssignment_0_3_3_1");
			builder.put(grammarAccess.getProjectAccess().getIndicatorAssignment_1_0_2(), "rule__Project__IndicatorAssignment_1_0_2");
			builder.put(grammarAccess.getProjectAccess().getIndicatorAssignment_1_0_3_1(), "rule__Project__IndicatorAssignment_1_0_3_1");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getNameAssignment_0_0(), "rule__KPIMeasurementDevice__NameAssignment_0_0");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getStatusAssignment_0_1_3(), "rule__KPIMeasurementDevice__StatusAssignment_0_1_3");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getParameterAssignment_0_1_4_3(), "rule__KPIMeasurementDevice__ParameterAssignment_0_1_4_3");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getLastCalculationAssignment_0_3_2(), "rule__KPIMeasurementDevice__LastCalculationAssignment_0_3_2");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getLastCalculationAssignment_0_3_3_1(), "rule__KPIMeasurementDevice__LastCalculationAssignment_0_3_3_1");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getNextCalculationAssignment_1_1(), "rule__KPIMeasurementDevice__NextCalculationAssignment_1_1");
			builder.put(grammarAccess.getLocationAccess().getLatAssignment_2(), "rule__Location__LatAssignment_2");
			builder.put(grammarAccess.getLocationAccess().getLongAssignment_6(), "rule__Location__LongAssignment_6");
			builder.put(grammarAccess.getDataValueAccess().getCollectedAssignment_1_1(), "rule__DataValue__CollectedAssignment_1_1");
			builder.put(grammarAccess.getDataValueAccess().getTypeAssignment_4(), "rule__DataValue__TypeAssignment_4");
			builder.put(grammarAccess.getDataValueAccess().getValueAssignment_6(), "rule__DataValue__ValueAssignment_6");
			builder.put(grammarAccess.getDataValueAccess().getProducedTimeAssignment_8(), "rule__DataValue__ProducedTimeAssignment_8");
			builder.put(grammarAccess.getDataValueAccess().getConsumedTimeAssignment_9_1(), "rule__DataValue__ConsumedTimeAssignment_9_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_0_0(), "rule__Parameter__NameAssignment_0_0");
			builder.put(grammarAccess.getParameterAccess().getUnitAssignment_0_4(), "rule__Parameter__UnitAssignment_0_4");
			builder.put(grammarAccess.getParameterAccess().getTypeAssignment_0_8(), "rule__Parameter__TypeAssignment_0_8");
			builder.put(grammarAccess.getParameterAccess().getGoalreferencevalueAssignment_0_13(), "rule__Parameter__GoalreferencevalueAssignment_0_13");
			builder.put(grammarAccess.getParameterAccess().getComponentAssignment_1_2(), "rule__Parameter__ComponentAssignment_1_2");
			builder.put(grammarAccess.getParameterAccess().getObservedValueAssignment_2_0_1(), "rule__Parameter__ObservedValueAssignment_2_0_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getNameAssignment_0_1(), "rule__BuildingComponent__NameAssignment_0_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getIsPartOfAssignment_0_3_1(), "rule__BuildingComponent__IsPartOfAssignment_0_3_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getComposedOfAssignment_1_2(), "rule__BuildingComponent__ComposedOfAssignment_1_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getComposedOfAssignment_1_3_1(), "rule__BuildingComponent__ComposedOfAssignment_1_3_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getLocationAssignment_2_2(), "rule__BuildingComponent__LocationAssignment_2_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getProducesAssignment_3_2(), "rule__BuildingComponent__ProducesAssignment_3_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getProducesAssignment_3_3_1(), "rule__BuildingComponent__ProducesAssignment_3_3_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getParameterAssignment_4_1(), "rule__BuildingComponent__ParameterAssignment_4_1");
			builder.put(grammarAccess.getBuildingComponentAccess().getDeviceAssignment_5_0_2(), "rule__BuildingComponent__DeviceAssignment_5_0_2");
			builder.put(grammarAccess.getBuildingComponentAccess().getDeviceAssignment_5_0_3_1(), "rule__BuildingComponent__DeviceAssignment_5_0_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getNameAssignment_0_1(), "rule__TransportationComponent__NameAssignment_0_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getIsPartOfAssignment_0_3_1(), "rule__TransportationComponent__IsPartOfAssignment_0_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getComposedOfAssignment_1_2(), "rule__TransportationComponent__ComposedOfAssignment_1_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getComposedOfAssignment_1_3_1(), "rule__TransportationComponent__ComposedOfAssignment_1_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getLocationAssignment_2_2(), "rule__TransportationComponent__LocationAssignment_2_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getProducesAssignment_3_2(), "rule__TransportationComponent__ProducesAssignment_3_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getProducesAssignment_3_3_1(), "rule__TransportationComponent__ProducesAssignment_3_3_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getParameterAssignment_4_1(), "rule__TransportationComponent__ParameterAssignment_4_1");
			builder.put(grammarAccess.getTransportationComponentAccess().getDeviceAssignment_5_0_2(), "rule__TransportationComponent__DeviceAssignment_5_0_2");
			builder.put(grammarAccess.getTransportationComponentAccess().getDeviceAssignment_5_0_3_1(), "rule__TransportationComponent__DeviceAssignment_5_0_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getNameAssignment_0_1(), "rule__EnvironmentalComponent__NameAssignment_0_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getIsPartOfAssignment_0_3_1(), "rule__EnvironmentalComponent__IsPartOfAssignment_0_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getComposedOfAssignment_1_2(), "rule__EnvironmentalComponent__ComposedOfAssignment_1_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getComposedOfAssignment_1_3_1(), "rule__EnvironmentalComponent__ComposedOfAssignment_1_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getLocationAssignment_2_2(), "rule__EnvironmentalComponent__LocationAssignment_2_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getProducesAssignment_3_2(), "rule__EnvironmentalComponent__ProducesAssignment_3_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getProducesAssignment_3_3_1(), "rule__EnvironmentalComponent__ProducesAssignment_3_3_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getParameterAssignment_4_1(), "rule__EnvironmentalComponent__ParameterAssignment_4_1");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getDeviceAssignment_5_0_2(), "rule__EnvironmentalComponent__DeviceAssignment_5_0_2");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getDeviceAssignment_5_0_3_1(), "rule__EnvironmentalComponent__DeviceAssignment_5_0_3_1");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getValueAssignment_4(), "rule__GoalReferenceValue__ValueAssignment_4");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getTypeAssignment_8(), "rule__GoalReferenceValue__TypeAssignment_8");
			builder.put(grammarAccess.getGoalReferenceValueAccess().getBasisAssignment_10_2(), "rule__GoalReferenceValue__BasisAssignment_10_2");
			builder.put(grammarAccess.getAggregatedValueAccess().getValueAssignment_3(), "rule__AggregatedValue__ValueAssignment_3");
			builder.put(grammarAccess.getAggregatedValueAccess().getTypeAssignment_6(), "rule__AggregatedValue__TypeAssignment_6");
			builder.put(grammarAccess.getAggregatedValueAccess().getAggregatorAssignment_9(), "rule__AggregatedValue__AggregatorAssignment_9");
			builder.put(grammarAccess.getAggregatedValueAccess().getAggregatedTimeAssignment_10_2(), "rule__AggregatedValue__AggregatedTimeAssignment_10_2");
			builder.put(grammarAccess.getBasisAccess().getDescriptionAssignment_3(), "rule__Basis__DescriptionAssignment_3");
			builder.put(grammarAccess.getBasisAccess().getPrincipleTypeAssignment_5(), "rule__Basis__PrincipleTypeAssignment_5");
			builder.put(grammarAccess.getBasisAccess().getSourceAssignment_7(), "rule__Basis__SourceAssignment_7");
			builder.put(grammarAccess.getSensorAccess().getNameAssignment_1(), "rule__Sensor__NameAssignment_1");
			builder.put(grammarAccess.getSensorAccess().getTypeAssignment_5(), "rule__Sensor__TypeAssignment_5");
			builder.put(grammarAccess.getActuatorAccess().getNameAssignment_1(), "rule__Actuator__NameAssignment_1");
			builder.put(grammarAccess.getActuatorAccess().getTypeAssignment_5(), "rule__Actuator__TypeAssignment_5");
			builder.put(grammarAccess.getProjectAccess().getUnorderedGroup(), "rule__Project__UnorderedGroup");
			builder.put(grammarAccess.getKPIMeasurementDeviceAccess().getUnorderedGroup(), "rule__KPIMeasurementDevice__UnorderedGroup");
			builder.put(grammarAccess.getParameterAccess().getUnorderedGroup(), "rule__Parameter__UnorderedGroup");
			builder.put(grammarAccess.getBuildingComponentAccess().getUnorderedGroup(), "rule__BuildingComponent__UnorderedGroup");
			builder.put(grammarAccess.getTransportationComponentAccess().getUnorderedGroup(), "rule__TransportationComponent__UnorderedGroup");
			builder.put(grammarAccess.getEnvironmentalComponentAccess().getUnorderedGroup(), "rule__EnvironmentalComponent__UnorderedGroup");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private ScmlGrammarAccess grammarAccess;

	@Override
	protected InternalScmlParser createParser() {
		InternalScmlParser result = new InternalScmlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public ScmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
