/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ScmlUiModule extends AbstractScmlUiModule {

	public ScmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
