/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big.ide;

import ac.at.tuwien.big.ScmlRuntimeModule;
import ac.at.tuwien.big.ScmlStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ScmlIdeSetup extends ScmlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ScmlRuntimeModule(), new ScmlIdeModule()));
	}
	
}
