/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ScmlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ac/at/tuwien/big/parser/antlr/internal/InternalScml.tokens");
	}
}
