/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big.parser.antlr;

import ac.at.tuwien.big.parser.antlr.internal.InternalScmlParser;
import ac.at.tuwien.big.services.ScmlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ScmlParser extends AbstractAntlrParser {

	@Inject
	private ScmlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalScmlParser createParser(XtextTokenStream stream) {
		return new InternalScmlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SmartCity";
	}

	public ScmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ScmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
