/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import scml.xtext.ui.internal.XtextActivator;

public class ScmlUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("ac.at.tuwien.big.Scml");
	}

}
