/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScmlRuntimeModule extends AbstractScmlRuntimeModule {
}
