/*
 * generated by Xtext 2.31.0
 */
package ac.at.tuwien.big;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ScmlStandaloneSetup extends ScmlStandaloneSetupGenerated {

	public static void doSetup() {
		new ScmlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
